REAL FUNCTION PSAT_F (A, B, C, D, E, T)
  IMPLICIT NONE

  REAL :: A, B, C, D, E, T

  PSAT_F = EXP(A + (B/T) + C*LOG(T) + D*T**E)

END FUNCTION PSAT_F

REAL FUNCTION GAMMA1_F (A, B, X1, X2, R, T)
  IMPLICIT NONE

  REAL :: A, B, X1, X2, R, T

  GAMMA1_F = EXP((A*((B*X2)/(A*X1 + B*X2))**2)/(R*T))

END FUNCTION GAMMA1_F

REAL FUNCTION GAMMA2_F (A, B, X1, X2, R, T)
  IMPLICIT NONE

  REAL :: A, B, X1, X2, R, T

  GAMMA2_F = EXP((B*((A*X1)/(A*X1 + B*X2))**2)/(R*T))

END FUNCTION GAMMA2_F

REAL FUNCTION PA_F (X1, X2, GAMMA1, GAMMA2, PSAT1, PSAT2, PHI1, PHI2)
  IMPLICIT NONE

  REAL :: X1, X2, GAMMA1, GAMMA2, PSAT1, PSAT2, PHI1, PHI2

  PA_F = ((X1*GAMMA1*PSAT1)/(PHI1))+((X2*GAMMA2*PSAT2)/(PHI2))

END FUNCTION PA_F

REAL FUNCTION Y_F (X, GAMMA, PSAT, PHI, PA)
  IMPLICIT NONE

  REAL :: X, GAMMA, PSAT, PHI, PA

  Y_F = X*GAMMA*PSAT/(PHI*PA)

END FUNCTION Y_F
